version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - 5003:5003
    environment:
      - WORKERS=1
      - PORT=5003
      - TIMEOUT=60
      - MAX_REQUESTS=500
      - BACKEND_TYPE=DATALAKE  # DATALAKE or BLOBSTORAGE
      - AZURE_TENANT_ID
      - AZURE_NAME
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - WEIGHTS_LOCATION=cooked/vectorisation/model_weights/detector.h5
