apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: textbox
  name: textbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: textbox
  template:
    metadata:
      labels:
        app: textbox
    spec:
      containers:
      - name: textbox
        image: textbox:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: textbox-conf
          - secretRef:
              name: azure-storage
